version: '3'

services:
  ubuntu:
    build: .
    container_name: ubuntu
    volumes:
      - /volume2/homes/wangrunxin/certbot/data:/etc/letsencrypt/
      - /volume2/homes/wangrunxin/certbot/config:/etc/certbot/
    network_mode: "host"
    tty: true
